export const Districts = [
  "Barguna",
  "Barisal",
  "Bhola ",
  "Bogra ",
  "Bandarban ",
  "Brahmanbaria",
  "Bagerhat",
  "Chandpur",
  "Chittagong",
  "Comilla ",
  "Cox's Bazar",
  "Chuadanga ",
  "Dhaka",
  "Dinajpur",
  "Faridpur",
  "Feni",
  "Gazipur",
  "Gopalganj",
  "Gaibandha ",
  "Habiganj",
  "Jamalpur",
  "Joypurhat",
  "Jhalokati ",
  "Jessore ",
  "Jhenaidah ",
  "Kishoreganj",
  "Kurigram",
  "Khagrachari ",
  "Kushtia",
  "Khulna",
  "Lalmonirhat ",
  "Lakshmipur",
  "Madaripur",
  "Manikganj",
  "Munshiganj",
  "Mymensingh",
  "Maulvibazar ",
  "Magura",
  "Meherpur",
  "Narayanganj",
  "Narsingdi",
  "Netrokona",
  "Naogaon",
  "Natore",
  "Nawabganj ",
  "Nilphamari",
  "Noakhali",
  "Narail",
  "Pabna ",
  "Panchagarh",
  "Patuakhali",
  "Pirojpur ",
  "Rajbari",
  "Rajshahi",
  "Rangpur ",
  "Rangamati ",
  "Shariatpur",
  "Sherpur",
  "Sunamganj ",
  "Sylhet",
  "Satkhira",
  "Sirajgonj",
  "Tangail",
  "Thakurgaon",
];
